apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: keycloak-instance
  namespace: default
  annotations:
    template-version: 1.0.0
spec:
  template:
    metadata:
      name: keycloak-template
    parameters:
    - name: APP_NAME
      value: keycloak
    - name: NAMESPACE
      value: default
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: admin