apiVersion: tmax.io/v1
kind: Template
metadata:
  name: keycloak-template
  namespace: default
  annotations:
    template-version: 1.0.0
spec:
  objects:
  - fields:
      apiVersion: v1
      kind: Service
      metadata:
        name: ${APP_NAME}-service
        namespace: ${NAMESPACE}
        labels:
          app: ${APP_NAME}
      spec:
        ports:
        - name: http
          port: 8080
          targetPort: 8080
        selector:
          app: ${APP_NAME}
        type: LoadBalancer
  - fields:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ${APP_NAME}
        namespace: ${NAMESPACE}
        labels:
          app: ${APP_NAME}
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: ${APP_NAME}
        template:
          metadata:
            labels:
              app: ${APP_NAME}
          spec:
            containers:
            - name: ${APP_NAME}
              image: quay.io/keycloak/keycloak:11.0.0
              env:
              - name: KEYCLOAK_USER
                value: ${KEYCLOAK_USER}
              - name: KEYCLOAK_PASSWORD
                value: ${KEYCLOAK_PASSWORD}
              - name: PROXY_ADDRESS_FORWARDING
                value: "true"
              ports:
              - name: http
                containerPort: 8080
              - name: https
                containerPort: 8443
              readinessProbe:
                httpGet:
                  path: /auth/realms/master
                  port: 8080
  parameters:
  - name: APP_NAME
    displayName: AppName
    description: AppName
    required: true
  - name: NAMESPACE
    displayName: Namespace
    description: Namespace
    required: true
  - name: KEYCLOAK_USER
    displayName: KeycloakUser
    description: KeycloakUser
    required: true
  - name: KEYCLOAK_PASSWORD
    displayName: KeycloakPassword
    description: KeycloakPassword
    required: true

