apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypercloud-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hypercloud-operator
  template:
    metadata:
      labels:
        name: hypercloud-operator
    spec:
      serviceAccountName: hypercloud-operator
      containers:
        - name: hypercloud-operator
          # Replace this with the built image name
          image: 172.22.11.2:30500/template-operator:latest
          command:
          - hypercloud-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hypercloud-operator"
